apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - image: rso-images:1.0.0-SNAPSHOT
        name: images
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://35.240.79.227:8080
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3


---

apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: images
